name: PVPControl
version: '${version}'
main: top.whcraft.pvpcontrol.Main
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - Dantiao
commands:
  pvpc:
    aliases: [pvpcontrol]
    description: Command help for AdsAutoMessage